# Generated by Django 5.2.7 on 2025-10-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0003_remove_userprofile_followers_followrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                help_text="(private)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, help_text="years (private)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="equipment_text",
            field=models.TextField(
                blank=True,
                help_text="List your available equipment (e.g., dumbbells 5–12kg, resistance bands medium, exercise bike, etc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height_cm",
            field=models.FloatField(blank=True, help_text="cm (private)", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight_kg",
            field=models.FloatField(blank=True, help_text="kg (private)", null=True),
        ),
    ]
