# Generated by Django 5.2.7 on 2025-10-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_userprofile_gender_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='plan_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
