# Generated by Django 5.2.7 on 2025-11-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fitness",
            "0008_trainingplan_plan_title_alter_trainingplan_plan_json_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="plan_preferences",
            field=models.TextField(blank=True, null=True),
        ),
    ]
